import os

Import('*')
sources = all('cs', 'snk')

refs = [
    'System',
    'System.Xml'
]

r = net.CLIRefs(refpaths, refs)
lib = net.CLILibrary('xmlrpc', sources, ASSEMBLYREFS=r)

#other pieces may want to target this
refpaths.append(os.getcwd())
