import os

Import('*')
sources = all('cs', 'snk')

refs = [
    'System', 
    'System.Web', 
    'System.Data',
    'avahi-sharp.dll', 
    'xmlrpc.dll',
    'ICSharpCode.SharpZipLib.dll'
]

r = net.CLIRefs(refpaths, refs)
lib = net.CLILibrary('daap-sharp', sources, ASSEMBLYREFS=r)
