#!/usr/bin/env python

"""
A process for processing file uploads.
"""

import sys

from filemq.configuration import *
from filemq.processingthread import FileProcessor

log = None

def main():
    # Initialize the config
    global config
    lconfig = base_logging
    if '--production' in sys.argv:
        update_config(production_config)
        lupdate_config(production_logging)
    elif '--live' in sys.argv:
        update_config(production_config)
        update_config(live_config)
        lupdate_config(production_logging)
    else:
        update_config(dev_config)
        lupdate_config(dev_logging)


    # Initialize Logging
    global log
    if '--debug' in sys.argv:
        lconfig['level'] = logging.DEBUG
    logging.basicConfig(**lconfig)
    log = logging.getLogger(__name__)
    handler = lconfig['handler'](*lconfig['handler_args'])
    log.addHandler(handler)

    log.debug('Starting with config: %s and logging %s',
        config, lconfig)

    fp = FileProcessor()

if __name__ == '__main__':
    print "Starting file upload process"
    main()
