#!/usr/bin/python
import os, sys
from popen2 import popen2

os.chdir(os.path.join(
		'masterapp', 'masterapp', 'public', 'javascripts', 'player'))
for file in os.listdir('.'):
	if file[0] == '.' or file.endswith('.orig'):
		continue
	stdout, stdin = popen2('jslint %s' % file)
	if 'No problems found in' not in stdout.readline():
		print 'JSLint failed for %s!' % file
		sys.exit(1)
