#!/usr/bin/env python
import sys
import gc
import fileprocess
from fileprocess.processingthread import FileUploadThread, set_fp
import logging
import signal
import threading
import socket
import cPickle
from sizer import annotate, scanner, formatting, operations
pickle = cPickle
from fileprocess.configuration import *
from operator import itemgetter

log = None
msock = None
fsock = None

HEAP_DETAILS = 2

def main():
    # Initialize the config
    global config
    lconfig = base_logging
    if '--production' in sys.argv:
        config.update(production_config)
        lconfig.update(production_logging)
    elif '--live' in sys.argv:
        config.update(production_config)
        config.update(live_config)
        lconfig.update(production_logging)
    else:
        config.update(dev_config)
        lconfig.update(dev_logging)

    # Initialize Logging
    global log
    logging.basicConfig(**lconfig)
    log = logging.getLogger(__name__)
    handler = lconfig['handler'](*lconfig['handler_args'])
    log.addHandler(handler)

    # Initialize the processing thread
    fp = FileUploadThread()
    set_fp(fp)

    # Initialize the monitoring thread
    mthread = threading.Thread(None, monitor, args = [fp])
    mthread.setDaemon(True)
    mthread.start()

    # Initialize the file socket
    global fsock
    fsock = socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    )
    port = config['port']
    fsock.bind(('localhost', port))
    fsock.listen(5)
    log.info("Bound to %d, ready to process files", port)
    while True:
        pfile = ''
        csock, caddr = fsock.accept()
        received = None
        while received != '':
            received = csock.recv(40)
            pfile = pfile + received

        fp.process(pickle.loads(pfile))


def monitor(pipeline):
    msock = socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    )
    msock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    msock.bind(('localhost', config['port']+1))

    msock.listen(2)

    baseline_objs = scanner.Objects()
    baseline_classes = annotate.simplegroupby(baseline_objs, classes=True)
    formatting.printsizes(baseline_classes, count=20)
    log.info("Monitor thread started")

    while True:
        try:
            csock, caddr = msock.accept()
            command = csock.recv(1)

            heap = {}
            if int(command) & HEAP_DETAILS:
                objs = scanner.Objects()
                classes = annotate.simplegroupby(objs, classes=True)
                diff = operations.diff(baseline_classes, classes)
                for key, c in diff.items():
                    if type(c.obj) == type:
                        heap[c.obj.__module__+'.'+c.obj.__name__] = c.size
                    else:
                        heap[c.show()] = c.size

                del objs
                del classes
                del diff

                heap = sorted(heap.items(), key=itemgetter(1), reverse=True)
                
            status = {
                'handlers': [], 
                'gc': gc.isenabled(),
                'heap': heap
            }
            for handler in pipeline.handlers:
                #size = classes[id(handler)].size
                waiting = list(handler.queue.queue)
                tuple = (handler.__class__.__name__, waiting, 0)
                status['handlers'].append(tuple)
                    
            
            del heap
            csock.sendall(pickle.dumps(status))
            csock.close()
        except Exception, e:
            log.exception("An exception occurred in the monitor")

if __name__ == '__main__':
    main()
